title: "Insurance Decoded"
tagline: "Cut Through the Jargon, Avoid Costly Mistakes"
description: >
  Real talk from a consumer who’s been there: Auto, Health, Home, Dental, 
  and Life insurance guides without the sales pitch.

hydejack:
  theme_color: "#2A5C8A"
  author:
    name: "Andrew Ortiz"
    email: a.ortiz2020@yahoo.com
  collections:
    auto-insurance:
      output: true
      permalink: /auto-insurance/:title
    health-insurance:
      output: true
      permalink: /health-insurance/:title
    life-insurance:
      output: true
      permalink: /life-insurance/:title
    travelers-insurance:
      output: true
      permalink: /travelers-insurance/:title
    pet-insurance:
      output: true
      permalink: /pet-insurance/:title
    misc-insurance:
      output: true
      permalink: /misc-insurance/:title
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap